# Generated by Django 4.0 on 2022-02-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_manager', '0002_alter_category_options_alter_food_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
